version: "2"
services:
  mariadb:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecretPassword
      MYSQL_USER: cellar
      MYSQL_PASSWORD: SecretPassword
      MYSQL_DATABASE: cellar
  thecellar:
    env_file:
      - mailsettings.env
    build:
      context: .
    image: thecellar:latest
    container_name: web
    ports:
      - 8080:8080
    environment:
      CELLAR_CON_STRING_DEV: jdbc:mysql://db/cellar
      CELLAR_USER_DEV: cellar
      CELLAR_PASS_DEV: SecretPassword
    links:
      - mariadb
