version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/data/thecellar/certs:/etc/nginx/certs:Z"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    privileged: true
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/data/thecellar/TheCellar/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:Z"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    privileged: true
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/data/thecellar/certs:/etc/nginx/certs:Z"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  mariadb:
    image: mariadb
    container_name: db
    volumes:
      - "/data/thecellar/mariadb:/var/lib/mysql:Z"
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecretPassword
      MYSQL_USER: cellar
      MYSQL_PASSWORD: SecretPassword
      MYSQL_DATABASE: cellar

  thecellar:
    env_file:
      - mailsettings.env
    build:
      context: .
    image: thecellar:latest
    container_name: web
    environment:
      CELLAR_CON_STRING_DEV: jdbc:mysql://db/cellar
      CELLAR_USER_DEV: cellar
      CELLAR_PASS_DEV: SecretPassword
      VIRTUAL_HOST: thecellar.vortexok.net
      LETSENCRYPT_HOST: thecellar.vortexok.net
      LETSENCRYPT_EMAIL: stephan.ellis@gmail.com
    links:
      - mariadb
