# Development Profile connected to local mysql
spring:
  profiles: dev
  datasource:
    url: ${CELLAR_CON_STRING_DEV}
    username: ${CELLAR_USER_DEV}
    password: ${CELLAR_PASS_DEV}
  jpa:
    properties:
      hibernate:
        ddl: none
        show_sql: true
        format_sql: true
  mail:
    host: localhost
    port: 25
    doNotReply: do-not-reply@thecellar.com

  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

  urls:
    server: localhost:8080
---
# Profile for production
spring:
  profiles: test
  datasource:
    url: ${CELLAR_CON_STRING_DEV}
    username: ${CELLAR_USER_DEV}
    password: ${CELLAR_PASS_DEV}
  jpa:
    properties:
      hibernate:
        ddl: none
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    doNotReply: the.cellar.stl@gmail.com
    username: the.cellar.stl@gmail.com
    password: MJU&nhy6BGT%vfr4
    properties:
      mail:
       smtp:
        auth: true
        starttls:
          enable: true
        ssl:
          enable: true
      socketFactory:
        port: 587
        class: javax.net.ssl.SSLSocketFactory
        fallback: false
    smtp:
      port: 587

  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

  urls:
    server: http://test.ronbreier.com
---
# Add more profiles below